# Use the README file as a reference to customize settings.

User:
  fields:
    default: full_name, email, crypted_password, salt, remember_me_token, remember_me_token_expires_at
    form: full_name, email, crypted_password, salt, remember_me_token, remember_me_token_expires_at
  relationships: authentications
  application: Application
